### ISSUE TITLE
docker-compose without mysql

### ISSUE THREAD

**Issue by StephanKrauss** [maurobonfietti/slim4-api-skeleton#37]
Sorry

**Comment by maurobonfietti** [comment]
Hi @StephanKrauss 

Yes, I also use slim in a docker container with an external MySQL database.

No problem. You need to set the MySQL connection in your **dotenv** file: `.env`:

```bash
DB_HOST='yourMySQLhostname'
DB_NAME='yourMySQLdatabase'
DB_USER='yourMySQLusername'
DB_PASS='yourMySQLpassword'
```

Previous answer:

https://github.com/maurobonfietti/slim4-api-skeleton/issues/27


Best regards.

Mauro.-
