### ISSUE TITLE
composer test no arranca, Tests: 4/4 

### ISSUE THREAD

**Issue by CraterMaik** [maurobonfietti/slim4-api-skeleton#46]
Buenas tengo este problema, tengo ya montado la base de datos en wamp en el localhost:82 y
he puesto tambien la db en .env:
DB_HOST='localhost:82'
DB_NAME='bdfutbol'
DB_USER='root'
DB_PASS=''

Pero sigue saliendo este problema

PHPUnit 9.4.2 by Sebastian Bergmann and contributors.

.F..                                                                4 / 4 (100%)

Time: 00:00.083, Memory: 6.00 MB

There was 1 failure:

1) Tests\integration\HomeTest::testGetStatus
Failed asserting that 500 matches expected 200.

C:\Users\assi\api\tests\integration\HomeTest.php:30

FAILURES!
Tests: 4, Assertions: 11, Failures: 1.
Script phpunit handling the test event returned with error code 1

**Comment by maurobonfietti** [comment]
Buenas!

El fin de semana (o cuando tenga tiempo libre), voy a hacer unos cambios para permitir configurar el puerto de conexion a la base de datos MySQL, usando alguna variable de entorno.

Algo similar a como ya hice en este PR en otro repositorio:

https://github.com/maurobonfietti/rest-api-slim-php/pull/127

Te aviso cuando este listo así podes probarlo nuevamente.

Saludos!

**Comment by maurobonfietti** [comment]
Buenas! Talvez ya lo resolviste a este tema...
De todos modos, hice unos pequeños cambios para permitir configurar el puerto a la conexion MySQL.

PR:
https://github.com/maurobonfietti/slim4-api-skeleton/pull/47

Version 0.30:
https://github.com/maurobonfietti/slim4-api-skeleton/releases/tag/0.30.0

Cierro este issue cualquier cosa lo vemos.
Saludos!
