### ISSUE TITLE
Add an option for setBasePath

### ISSUE THREAD

**Issue by kymodoke** [maurobonfietti/slim4-api-skeleton#6]
In order to suit different use cases : 
- for people installing their API project in a sub-folder (either for production or even more for a dev/test environment)
- for people deporting only content of "public" folder to the exposed htdocs folder of the vhost, while the rest of the application is located in a parent folder (not exposed).

it would be interesting to add $app->setBasePath(xxx) where the basepath could be defined in .env file. _Note: just after after `$app = AppFactory::create` in src/App/App.php_

**Comment by maurobonfietti** [comment]
Hi @kymodoke 

I released a **new version 0.0.7**, that add an option for setBasePath().

Added new env var: "SLIM_BASE_PATH", to allow running Slim in a subdirectory.

Pull Request: #9 

Thanks for you suggestion!
