### ISSUE TITLE
Abandoned Packages Updated

### ISSUE THREAD

**Issue by mrevjd** [maurobonfietti/slim4-api-skeleton#60]
Great package to get started with slim 4 and APIs.

While setting up this I noticed the following errors:
```
Package object-calisthenics/phpcs-calisthenics-rules is abandoned, you should avoid using it. Use symplify/phpstan-rules instead.
Package sebastian/finder-facade is abandoned, you should avoid using it. No replacement was suggested.
```
These were dependencies of nunomaduro/phpinsights v1.14.1
On researching I found that nunomaduro/phpinsights has made some changes and has now released v2.0.1

I have updated the composer.json as shown below:
`        "nunomaduro/phpinsights": "^2.0",`

Basic tests seem to work.

**Comment by maurobonfietti** [comment]
Tested & Merged.
Thank you very much Evan @mrevjd !
