### ISSUE TITLE
Error , could not find driver

### ISSUE THREAD

**Issue by qwertz1958** [maurobonfietti/slim4-api-skeleton#74]
Hello, when i call 
php console api:generate:endpoints test
i get the message

> could not find driver

Who can help.

Your sincerly

Stephan

**Comment by maurobonfietti** [comment]
Hi Stephan @qwertz1958 :wave:

Do you have the PDO driver for MySQL configured on your local server?

You can check this with a `phpinfo()` or running `php -m` to see if you have it enabled.

In my case I have this:

<img width="1187" alt="Screen Shot 2022-01-04 at 10 14 33" src="https://user-images.githubusercontent.com/24535949/148064777-4c87c357-feb7-413f-b68c-a694f4022abb.png">

<img width="659" alt="Screen Shot 2022-01-04 at 10 16 44" src="https://user-images.githubusercontent.com/24535949/148064804-b2f6419f-5cb1-46d4-9ca6-c00302b232ed.png">
